### PR TITLE
enhancement: fylr k8s deployment

### PR DESCRIPTION
**Pull request by leonsteinhaeuser**
This PR improves the documentation for the use of fylr in K8s.

### CODE REVIEW

**Comment by KlausThornProgrammfabrik** [comment]
- please update the top-level-README.md [README.md](https://github.com/programmfabrik/fylr-install#readme): link to kubernetes-readme and remove "will be linked when updated." where approprate. In main, the top-level README.md is already different, maybe merge the changes from main into your branch?
- the kubernetes/ has no README.md. maye change this and put some first steps there that are not specific to execserver or fylr? Maybe move parts of the flyr/readme here.
- the kubernetes/execserver#readme has only a deploy step... maybe this is exatly right, but make sure you put yourself into the shoes of the reader, what could he forget? e.g. have the needed resources? 
- instead of writing `"Kustomization" file` I would suggest to write `kustomization.yaml file` so that the reader does not have to guess which file where you mean

**Comment by KlausThornProgrammfabrik** [comment]
- I suggest to replace examples with customer names like `namespace: fylr-unib-heidelberg` with `namespcae: example`
- I suggest to replace placeholders like `<external-url>` with https://example.com
- I suggest then to write in the READMEs: search for all instances of "example" and replace them
- I suggest to make a chapter in a README called "choosing a version" and explain what options there are (main, unstable, link to release-history with version numerbs) and specify where to put it, so for example point to the file(s) with `image: docker.fylr.io/fylr/fylr:main`

**Comment by KlausThornProgrammfabrik** [comment]
- I suggest to put into `kubernetes/fylr/config/fylr.yaml` a comment line, on top, with a link to the official docs of that file (what could go in there, syntax, etc.). For all config files of programmfabrik software, so also for execserver. It would be nice to do it also for other files, like kubernetes.

**Comment by KlausThornProgrammfabrik** [comment]
- In the to-be-created `kubernetes/readme` I suggest to make a paragraph named requirements, where the "kubernetes with at least version ..." goes, moved from the `kubernetes/fylr#readme`. I write "paragraph" because I assume that we will need the headline of that paragraph (requirements) to link to later when communicating with customers or writing other docs

**Comment by leonsteinhaeuser** [comment]
Most of the comments you wrote are not necessary, because if someone wants to use Kubernetes to deploy fylr, we can assume that he/she already knows how to work with it. In the Kubernetes community, it is not common to describe in detail how to change values in the customization files, as they should normally be left untouched. The only parts that really need to be changed are the files inside the configuration folder.

> instead of writing "Kustomization" file I would suggest to write kustomization.yaml file so that the reader does not have to guess which file where you mean

I won't do that, because the tool itself is called "Kustomization".

> I suggest to replace placeholders like <external-url> with https://example.com/

Not every place that takes the external URL should be prefixed with the protocol (http/https). I will leave it that way.

> I suggest then to write in the READMEs: search for all instances of "example" and replace them

This is already included. See: `However, some settings still need to be changed. For example, the `<external-url>` placeholder needs to be replaced with the actual external URL of the service.`

> I suggest to make a chapter in a README called "choosing a version" and explain what options there are (main, unstable, link to release-history with version numerbs) and specify where to put it, so for example point to the file(s) with image: docker.fylr.io/fylr/fylr:main

We do not have a scheme yet. Currently we only support **main**.

> I suggest to put into kubernetes/fylr/config/fylr.yaml a comment line, on top, with a link to the official docs of that file (what could go in there, syntax, etc.). For all config files of programmfabrik software, so also for execserver. It would be nice to do it also for other files, like kubernetes.

We do not have official documentation yet.

> In the to-be-created kubernetes/readme I suggest to make a paragraph named requirements, where the "kubernetes with at least version ..." goes, moved from the kubernetes/fylr#readme. I write "paragraph" because I assume that we will need the headline of that paragraph (requirements) to link to later when communicating with customers or writing other docs

This should not be necessary as we do not use a special API. Almost any version should be able to run with these files. The oldest version I tested with was 1.19.x. Since Kubernetes has a relatively short EOL cycle, we should basically tell the end user to use a supported version.

**Pull request merged**
